/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pis.project;

public class App {
    public static void main(String[] args) {
        SnakeGameGUI.main(new String[0]);
    }
}
